name: launch_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  dio: ^5.4.1
  icons_plus: ^5.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  iconsax: ^0.0.8
  get_storage: ^2.1.1
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  device_info_plus: ^10.0.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: BinancePlex
      fonts:
        - asset: assets/font/BinancePlex.ttf